name: recipe_gpt
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.1.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # flutter packages pub run build_runner clean
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

# flutter packages pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/launcher/appIcon.png"
  image_path_android: "assets/icons/launcher/appIcon.png"
  adaptive_icon_background: "assets/icons/launcher/background.png"
  adaptive_icon_foreground: "assets/icons/launcher/foreground.png"
  windows:
    generate: true
    image_path: "assets/icons/launcher/appIconWindows.png"
    icon_size: 187

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#292A36"
  image: assets/icons/launcher/appIcon.png
#   android_12:
#     image: assets/icons/launcher/splash.png
#     color: "#292A36"
#   web: false


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/scripts/
    # - lib/i18n/